[build]
  publish = "."
  functions = "Netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "sb_publishable"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
