[build]
  publish = "."
  functions = "Netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build]
  publish = "."
  functions = "Netlify/functions"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
